TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += devKS_34980A_EPICS.db
DB += devKS_34980A_EPICS.proto

#=======================================
include $(TOP)/configure/RULES
